FROM nginx
WORKDIR /app
RUN cat /usr/share/nginx/html/index.html \ 
    && chmod 777 /usr/share/nginx/html/index.html
ENV VALUE Welcome to HTML Hell 

COPY entrypoint.sh  /app/entrypoint.sh

RUN chmod u+x entrypoint.sh && ls && cat entrypoint.sh

CMD ["./entrypoint.sh"]
